<?php

/**
 * Implements hook_permission().
 */
function drucars_permission() {
  
  $permission = array(
    'drucars view' => array(
      'title' => t('View drucars items'),
      'description' => t('User with this access right can view drucars items.'),
    ),
    'drucars edit' => array(
      'title' => t('Edit drucars items'),
      'description' => t('User with this access right can manage drucars items.'),
    ),
  );

  return $permission;
}

/**
 * Implements hook_menu().
 */
function drucars_menu() {
  
  $items['drucars'] = array(
    'title' => 'Drucars',
    'page callback' => 'drucars_main_page',
    'access arguments' => array('drucars view'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/list'] = array(
    'title' => 'List cars',
    'access arguments' => array('drucars view'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['drucars/add'] = array(
    'title' => 'Add a car',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_edit_car_form'),
    'access arguments' => array('drucars edit'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/%'] = array(
    'title' => 'Drucars',
    'title callback' => 'drucars_view_car_title',
    'title arguments' => array(1),
    'page callback' => 'drucars_view_car',
    'page arguments' => array(1),
    'access arguments' => array('drucars view'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/drucars.ui.inc',
  );

  $items['drucars/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['drucars/%/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_edit_car_form', 1),
    'access arguments' => array('drucars edit'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'inc/drucars.ui.inc',
  );

  $items['drucars/%/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_delete_car_form', 1),
    'access arguments' => array('drucars edit'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'file' => 'inc/drucars.ui.inc',
  );

  return $items;
}

function drucars_view_car_title($cid) {
  $car = new Car($cid);
  return $car->getLicensePlate() . ' - ' . $car->getModel();
}

/**
 * Implements hook_theme().
 */
function drucars_theme($existing, $type, $theme, $path) {
  return array(
    'drucars_view_car' => array(
      'variables' => array('car' => null),
      'template' => 'tpl/drucars_view_car',
    ),
    'drucars_list_cars' => array(
      'variables' => array('cars' => null, 'pager' => null),
      'template' => 'tpl/drucars_list_cars',
    ),
  );
}

function drucars_load_cars() {

  $cars = array();

  $rows = db_select('drucars', 'd')
    ->extend('PagerDefault')
    ->fields('d')
    ->limit(10)
    ->execute()
	  ->fetchAll();

  foreach ($rows as $row) {
    $car = new Car();
    $car->loadPropertiesFromObject($row);
    $cars[] = $car;
  }

  return $cars;
}

function drucars_load_cars_with_pager() {
  return array(
   'cars' => drucars_load_cars(),
   'pager' => theme('pager'),
  );
}