<?php

/**
 * Implements hook_permission().
 */
function drucars_permission() {
  
  $permission = array(
    'drucars view' => array(
      'title' => t('View drucars items'),
      'description' => t('User with this access right can view drucars items.'),
    ),
    'drucars edit' => array(
      'title' => t('Edit drucars items'),
      'description' => t('User with this access right can manage drucars items.'),
    ),
  );
  
  return $permission;
}

/**
 * Implements hook_menu().
 */
function drucars_menu() {
  
  $items['drucars'] = array(
    'title' => 'Drucars',
    'page callback' => 'drucars_main_page',
    'access arguments' => array('drucars view'),
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/view/%'] = array(
    'page callback' => 'drucars_view_car',
    'page arguments' => array(2),
    'access arguments' => array('drucars view'),
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/add'] = array(
    'title' => 'Add a car',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_edit_car_form'),
    'access arguments' => array('drucars edit'),
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/edit/%'] = array(
    'title' => 'Add a car',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_edit_car_form', 2),
    'access arguments' => array('drucars edit'),
    'file' => 'inc/drucars.ui.inc',
  );
  
  $items['drucars/delete/%'] = array(
    'title' => 'Delete a car',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drucars_delete_car_form', 2),
    'access arguments' => array('drucars edit'),
    'file' => 'inc/drucars.ui.inc',
  );
  
  return $items;
}

/**
 * Implements hook_theme().
 */
function drucars_theme($existing, $type, $theme, $path) {
  return array(
    'drucars_view_car' => array(
      'variables' => array('car' => null),
      'template' => 'tpl/drucars_view_car',
    ),
    'drucars_list_cars' => array(
      'variables' => array('cars' => null, 'pager' => null),
      'template' => 'tpl/drucars_list_cars',
    ),
  );
}

function drucars_load_cars() {
  
  $cars = array();
  
  $rows = db_select('drucars', 'd')
    ->extend('PagerDefault')
    ->fields('d')
    ->limit(10)
    ->execute()
	  ->fetchAll();
  
  foreach ($rows as $row) {
    $car = new Car();
    $car->loadPropertiesFromObject($row);
    $cars[] = $car;
  }
  
  $result = array(
    'cars' => $cars,
    'pager' => theme('pager'),
  );

  return $result;
}